version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: blood_test_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: blood_test_postgres
    environment:
      POSTGRES_DB: blood_test_analysis
      POSTGRES_USER: blood_test_user
      POSTGRES_PASSWORD: blood_test_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: blood_test_api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://blood_test_user:blood_test_password@postgres:5432/blood_test_analysis
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  celery_worker:
    build: .
    container_name: blood_test_worker
    command: celery -A celery_app worker --loglevel=info --concurrency=2
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://blood_test_user:blood_test_password@postgres:5432/blood_test_analysis
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  celery_beat:
    build: .
    container_name: blood_test_beat
    command: celery -A celery_app beat --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://blood_test_user:blood_test_password@postgres:5432/blood_test_analysis
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  flower:
    build: .
    container_name: blood_test_flower
    command: celery -A celery_app flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://blood_test_user:blood_test_password@postgres:5432/blood_test_analysis
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data: 